### ISSUE TITLE
No support for @DBRef

### ISSUE THREAD

**Issue by lkaupp** [agoston/spring-data-mongodb-encrypt#21]
As soon as i use @Encrypted on a sub-class referenced by @DBRef using spring-data-mongo i got this execption:
```
java.lang.ClassCastException: class com.mongodb.DBRef cannot be cast to class org.bson.Document (com.mongodb.DBRef and org.bson.Document are in unnamed module of loader 'app')
	at com.bol.secure.CachedEncryptionEventListener.cryptFields(CachedEncryptionEventListener.java:80) ~[spring-data-mongodb-encrypt-2.2.jar:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptList(CachedEncryptionEventListener.java:101) ~[spring-data-mongodb-encrypt-2.2.jar:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptFields(CachedEncryptionEventListener.java:84) ~[spring-data-mongodb-encrypt-2.2.jar:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptDocument(CachedEncryptionEventListener.java:132) ~[spring-data-mongodb-encrypt-2.2.jar:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptFields(CachedEncryptionEventListener.java:80) ~[spring-data-mongodb-encrypt-2.2.jar:na]
	at com.bol.secure.CachedEncryptionEventListener.onBeforeSave(CachedEncryptionEventListener.java:64) ~[spring-data-mongodb-encrypt-2.2.jar:na]
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:89) ~[spring-data-mongodb-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:31) ~[spring-data-mongodb-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]

```
Code:
```
@Document
public class User{
 @DBRef
    private List<TransactionRecord> transactions = new ArrayList<>();
}
@Document
public class TransactionRecord {
     @Encrypted
    private final String userId;
}

```

**Comment by agoston** [comment]
DBRef is a weird abomination, it informs **mongodb client** to initiate yet-another lookup for another document. So it's all client-side. That's why I never imagined anyone would try to use it, and I also skipped testing it.

I can run some tests and try to cover it, but it's quite complex, with all the functionality implemented client-side, and the use cases are relatively low, so I can't assign high prio for this one.

**Comment by CloudResearch** [comment]
I use @DBRef quite alot, in order to integrate other documents and not queried often over my e.g. User Entity. So it is possible to query it standalone and in fast fashion directly and also have a loose coupled link to my entity from my user, that is fully lazyloaded and the document is only queried if i need to (spare times).

**Comment by agoston** [comment]
Thanks :)

Will keep this bug open, as indeed this is a shortcoming that others might run into as well. It's best to be open about it.

**Comment by KhalilHadded** [comment]
is there a solution for this?

**Comment by agoston** [comment]
DbRef is a hackish convenience shortcut. I never had to use it, and especially with joins in mongodb 4, I don't see any reason to keep using it.

I'm more than happy to merge a pull request for it, but I don't expect to have the time for this in the short future.

**Comment by rrkheloufi** [comment]
Any update about this problem ?

**Comment by agoston** [comment]
As always, I welcome PRs, but I don't want to spend time on this functionality for the reasons explained above.
